In [58]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(420)

In [3]:
fastball_speed = np.random.randint(90, 106, size=500)

In [6]:
tommy_john = np.where(fastball_speed > 96, np.random.choice([0, 1], size=500, p=[0.3, 0.7]), 0)

In [7]:
d = {'fastball_speed': fastball_speed, 'tommy_john': tommy_john}

In [8]:
df = pd.DataFrame(data = d)

In [10]:
df.head()

fastball_speed  tommy_john
0              91           0
1              98           1
2              96           0
3             105           1
4             105           1

In [11]:
X = df[['fastball_speed']]

In [12]:
y = df[['tommy_john']]

## **_Normal Train Test Split_**

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr = LogisticRegression()

In [17]:
lr.fit(X_train, y_train.values.ravel())

LogisticRegression()

In [18]:
lr.score(X_test, y_test)

0.77

## **_Test this again_**

In [19]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X, y, test_size=0.2, random_state=25)

In [20]:
lr.fit(X2_train, y2_train.values.ravel())

LogisticRegression()

In [21]:
lr.score(X2_test, y2_test)

0.75

## **_Basic Cross Val_**

In [22]:
from sklearn.model_selection import cross_val_score

In [24]:
cv = cross_val_score(lr, X, y.values.ravel(), cv=10)

In [25]:
cv

array([0.72, 0.7 , 0.82, 0.76, 0.56, 0.7 , 0.86, 0.82, 0.72, 0.72])

In [26]:
np.average(cv)

np.float64(0.7379999999999999)

In [27]:
np.std(cv)

np.float64(0.08022468448052629)

### _**Define Standard Kfold**_

In [28]:
from sklearn.model_selection import KFold

In [34]:
kf = KFold(n_splits=15, shuffle=True, random_state=42)

In [35]:
kfscore = cross_val_score(lr, X, y.values.ravel(), cv=kf, scoring='f1')

In [36]:
kfscore2 = cross_val_score(lr, X, y.values.ravel(), cv=kf, scoring='accuracy')

In [37]:
kfscore

array([0.8       , 0.61538462, 0.75675676, 0.66666667, 0.53846154,
       0.66666667, 0.64      , 0.69565217, 0.75      , 0.59259259,
       0.76470588, 0.68965517, 0.77777778, 0.53846154, 0.77419355])

In [38]:
np.average(kfscore)

np.float64(0.6844649953223352)

In [39]:
np.std(kfscore)

np.float64(0.08353674053796907)

In [40]:
kfscore2

array([0.79411765, 0.70588235, 0.73529412, 0.73529412, 0.64705882,
       0.78787879, 0.72727273, 0.78787879, 0.81818182, 0.66666667,
       0.75757576, 0.72727273, 0.75757576, 0.63636364, 0.78787879])

In [41]:
np.average(kfscore2)

np.float64(0.7381461675579323)

In [42]:
np.std(kfscore2)

np.float64(0.0533998270042147)

## **_Startified K Fold_**

In [43]:
from sklearn.model_selection import StratifiedKFold

In [44]:
kfs = StratifiedKFold(n_splits=10, shuffle=True, random_state=11)

In [45]:
kfsscore =cross_val_score(lr, X, y.values.ravel(), cv=kfs)

In [46]:
kfsscore

array([0.62, 0.76, 0.7 , 0.74, 0.76, 0.7 , 0.8 , 0.84, 0.66, 0.8 ])

In [47]:
np.average(kfsscore)

np.float64(0.738)

In [48]:
np.std(kfsscore)

np.float64(0.06477653896280659)

## **_Pipeline Example_**

In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
scaler = StandardScaler()

In [51]:
from sklearn.pipeline import make_pipeline

In [52]:
pipe = make_pipeline(scaler, lr)

In [53]:
pipe.fit(X_train, y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [55]:
scorepipe = cross_val_score(pipe, X, y.values.ravel(), cv=10)
scorepipe

array([0.72, 0.7 , 0.82, 0.76, 0.56, 0.7 , 0.86, 0.82, 0.72, 0.72])

In [56]:
np.average(scorepipe)

np.float64(0.7379999999999999)

In [57]:
np.std(scorepipe)

np.float64(0.08022468448052629)